### ISSUE TITLE
Error message when using the play command.

### ISSUE THREAD

**Issue by CharliePlayz** [Aayush-683/BrokenDisc#30]
Error: Error: Cannot find module '/home/runner/BrokenDisc/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.24/opus.node'
Require stack:
- /home/runner/BrokenDisc/node_modules/@discordjs/opus/lib/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/util/loader.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/index.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/index.js
- /home/runner/BrokenDisc/src/index.js
Error: Cannot find module 'node-opus'
Require stack:
- /home/runner/BrokenDisc/node_modules/prism-media/src/util/loader.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/index.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/index.js
- /home/runner/BrokenDisc/src/index.js
Error: Cannot find module 'opusscript'
Require stack:
- /home/runner/BrokenDisc/node_modules/prism-media/src/util/loader.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/index.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/index.js
- /home/runner/BrokenDisc/src/index.js
    at Object.loader [as require] (/home/runner/BrokenDisc/node_modules/prism-media/src/util/loader.js:12:9)
    at loadOpus (/home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js:17:17)
    at new OpusStream (/home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js:46:10)
    at new Encoder (/home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js:149:5)
    at Object.transformer (/home/runner/BrokenDisc/node_modules/discord-player/node_modules/@discordjs/voice/dist/index.js:8:13311)
    at /home/runner/BrokenDisc/node_modules/discord-player/node_modules/@discordjs/voice/dist/index.js:8:16735
    at Array.map (<anonymous>)
    at We (/home/runner/BrokenDisc/node_modules/discord-player/node_modules/@discordjs/voice/dist/index.js:8:16726)
    at StreamDispatcher.createStream (/home/runner/BrokenDisc/node_modules/discord-player/dist/VoiceInterface/StreamDispatcher.js:116:62)
    at Queue.<anonymous> (/home/runner/BrokenDisc/node_modules/discord-player/dist/Structures/Queue.js:699:46)
Error: Error: Cannot find module '/home/runner/BrokenDisc/node_modules/@discordjs/opus/prebuild/node-v93-napi-v3-linux-x64-glibc-2.24/opus.node'
Require stack:
- /home/runner/BrokenDisc/node_modules/@discordjs/opus/lib/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/util/loader.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/Opus.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/opus/index.js
- /home/runner/BrokenDisc/node_modules/prism-media/src/index.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/smoothVolume.js
- /home/runner/BrokenDisc/node_modules/discord-player/dist/index.js

**Comment by Aayush-683** [comment]
seems like the opus module wasn't installed
> `npm i node-opus`
