### ISSUE TITLE
Youtube 404 error

### ISSUE THREAD

**Issue by darkangel655** [Aayush-683/BrokenDisc#8]
iniget/dist/index.js:196:27)
    at Object.onceWrapper (events.js:421:26)
    at ClientRequest.emit (events.js:314:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:122:17)
    at TLSSocket.socketOnData (_http_client.js:474:22)
    at TLSSocket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at TLSSocket.Readable.push (_stream_readable.js:213:10) {
  statusCode: 404

**Comment by Aayush-683** [comment]
Youtube Updated There API, im working on fixing it

**Comment by Aayush-683** [comment]
Update `node-ytdl` it looks like they fixed it in there package
